### PR TITLE
Just... general.txt

### PR DESCRIPTION
**Pull request by RickAucoin**
Added a few quotes, fixed a couple of small punctuation or spelling type items.

### CODE REVIEW

**Review by CargoVroom — CHANGES_REQUESTED** [review]
These are mostly good changes. I resent the removal of Are ya winnin son? But otherwise good.
Should probably be a PR against Dev or Dev-Savebreak tho

**Comment by RickAucoin** [comment]
> These are mostly good changes. I resent the removal of Are ya winnin son? But otherwise good. Should probably be a PR against Dev or Dev-Savebreak tho

I absolutely didn't intend to remove "Are ya winnin son". In fact I made sure not to remove anything, that wouldn't be cool.  I'll look at it and correct that right away.  Thank you!

**Comment by RickAucoin** [comment]
> > These are mostly good changes. I resent the removal of Are ya winnin son? But otherwise good. Should probably be a PR against Dev or Dev-Savebreak tho
> 
> I absolutely didn't intend to remove "Are ya winnin son". In fact I made sure not to remove anything, that wouldn't be cool. I'll look at it and correct that right away. Thank you!

So, put the PR in the Dev or Dev-Savebreak branch?  See, that's the kind of info I didn't know so thank you. :)

**Comment by RickAucoin** [comment]
>  I resent the removal of Are ya winnin son? 

I looked into the change on that quote and remembered what I did and why.  The line was on both 363 and 365, so it was duplicated on the original with only one line separating the two identical lines.


I removed the duplicate on 365 only, leaving the 363 in place.  My apologies, I should have commented what was done and why.


AreYaWinninSon

**Comment by RickAucoin** [comment]
>  I resent the removal of Are ya winnin son? 

I looked into the change on that quote and remembered what I did and why.  The line was on both 363 and 365, so it was duplicated on the original with only one line separating the two identical lines.


I removed the duplicate on 365 only, leaving the 363 in place.  My apologies, I should have commented what was done and why.


AreYaWinninSon

**Comment by RickAucoin** [comment]
>Should probably be a PR against Dev or Dev-Savebreak tho

I apologize, I've tried to figure out how exactly this is done, sending a PR against Dev (for example).  Any PR I produce for the general.txt seems to go to my own fork (which is a bit silly) or to master, which isn't correct procedure if I understand correctly.

Right now there's a draft PR in... my fork I made to work on the file?  

Any pointers in the right direction appreciated.  The information I've been reading via google or on githb itself isn't... clear.  

Thanks, sorry to bother you with such a small item.

**Pull request closed without merging**
