### PR TITLE
Change LanceSight2 and LanceSight3 to AllLanceSight

### PR DESCRIPTION
**Pull request by reddestmoon**
Here is a more controversal change. As far as I can tell there is no
difference at all in the bonus LanceSight2 and LanceSight3 and the
only difference between the bonuses LanceSight2 and LanceSight3 and
AllLanceSight is that LanceSight2 and LanceSight3 add a fixed amount
to the base value were AllLanceSight multiplies the base value with
a multiplier. I think this difference can be displayed by the
different formating of the values. But if that is not the case, let
me know what you prefer and I rework the commit.

### CODE REVIEW

**Comment by Hark0nnen** [comment]
No. +Base sight is different from multiplication, it was added specifically because users nitpicked.
But LanceSight2 is wrong on that two items that have it, it should be LanceSight3.

**Comment by reddestmoon** [comment]
Ok, one question, would it then not be more consistent to rename the bonus LanceSight3 to AllLanceSight2?

**Comment by Hark0nnen** [comment]
The internal names are irrelevant

**Comment by reddestmoon** [comment]
I have changed all items to use LanceSight3. As I am no git expert, please let me know if it is better, to close this pull request and create a new one with only the changes from LanceSight2 to LanceSight3.

**Pull request merged**
